/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.app;
 
 
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) { 
        System.out.println(WordUtils.capitalize("hello world"));
    }
}
